package org.apache.jsp.templates.hardsocket;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wQuality_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?v=1.2\"></script>  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?v=1.4\"></script> \r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?key=46ce9d0614bf7aefe0ba562f8cf87194&v=1.1&services=true\"></script>  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../site_media/js/jquery.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<title>水质检测</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" body,form,ul,li,a,ol,h1,h2,h3,h4,h5,h6,input,textarea,img{margin:0px;padding:0px;}  \r\n");
      out.write("ul,li,dl{list-style-type:none;} \r\n");
      out.write("a{text-decoration: none;}\r\n");
      out.write("body{font-size: 12px;font-family: \"Microsoft YaHei\";color:#777777; overflow:auto;background-color: #b0d7f9;}\r\n");
      out.write(".w_div{width: 100%;height: 1000px; }\r\n");
      out.write(".w_top{width: 100%;height: 50px;}\r\n");
      out.write(".w_top h1{text-align: center;font-weight: bold;color: black;font-size: 36px;margin-top: 5px;}\r\n");
      out.write(".w_content{width: 100%;height: auto;border: 1px solid blue;margin-top: 15px;}\r\n");
      out.write(".w_contentLeft{width: 55%; border: 1px solid blue;height: 900px;float: left;margin-right: 20px;margin-left: 10px;}\r\n");
      out.write(".w_contentRight{width: 42%;height: 900px;border: 1px solid blue;float: left;}\r\n");
      out.write(".w_logo{display: block;float: right;margin-top: -35px;margin-right: 30px;width: 70px;height: 40px;text-align: center;}\r\n");
      out.write(".w_conTop{width: 100%;float: left;height: 800px;border: 1px solid blue;margin-bottom: 25px;}\r\n");
      out.write(".w_conComm{width: 100%;height: auto;border: 1px solid red;}\r\n");
      out.write(".w_conComm input{display: block; width: 200px;height: 50px;margin-left: 150px;float: left;}\r\n");
      out.write(".w_contentRight ul{width: 100%;height: 45px;}\r\n");
      out.write(".w_contentRight li{float: left;text-align: center;width: 49%; height: 40px;background-color: #e5e5e5;border-right-color: black;}\r\n");
      out.write(".w_contentRight a{color: black;font-size: 24px;}\r\n");
      out.write(".w_conTab{width: 100%;height: auto;margin-top: 0px;}\r\n");
      out.write(".w_conTab table{width: 100%;height: auto;text-align: center;border: 1px solid black;}\r\n");
      out.write(".w_conTab table thead td{font-size: 22px;font-weight: 400;}\r\n");
      out.write(".w_conTab table td{font-size: 17px; border: 1px solid black;}\r\n");
      out.write(".w_conTab caption{font-size: 26px;}\r\n");
      out.write(".col{background-color: blue;color: white;}\r\n");
      out.write(".w_a{width: 100%;height: 35px;}\r\n");
      out.write(".w_a a{display: block; float: left;width: 50%;text-align: center;background-color: #e5e5e5;}\r\n");
      out.write(".w_a a:hover{background-color: white;color: black;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\r\n");
      out.write("// \t$(\".w_contentRight a\").hover(function(){\r\n");
      out.write("// \t\t$(\".w_contentRight a\").parent().css(\"background-color\", \"blue\");\r\n");
      out.write("\r\n");
      out.write("// \t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"w_div\">\r\n");
      out.write("\t\t<div class=\"w_top\"><h1>水质检测系统</h1><input type=\"button\" name=\"logo\" id=\"logo\" value=\"登录\" class=\"w_logo\"/></div>\r\n");
      out.write("\t\t<div class=\"w_content\">\r\n");
      out.write("\t\t\t<div class=\"w_contentLeft\">\r\n");
      out.write("\t\t\t\t<div class=\"w_conTop\" id=\"map\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w_contentRight\">\r\n");
      out.write("\t\t\t<div class=\"w_a\"><a href=\"#\">查看报表</a><a href=\"#\">查看曲线图</a></div>\r\n");
      out.write("<!-- \t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">查看报表</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">查看曲线图</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"w_conTab\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" id=\"conTab\">\r\n");
      out.write("\t\t\t\t\t\t<caption>自来水公司检测总览</caption>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr><th></td><td>浊度</td><td>PH值</td><td>余氯</td><td>电导率</td><td>溶解氧</td><td>水温</td></tr> \r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>总监测值</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfas</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfas</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfas</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfas</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfas</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasd</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>上海自来水公司</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfa</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>上海自来水公司</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>上海自来水公司</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>上海自来水公司</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t\t<td>dsafdfasdfaf</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w_conComm\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"company\" id=\"company\" value=\"自来水公司分布图\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"region\" id=\"region\" value=\"上海行政区分布图\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// var map = new BMap.Map(\"map\");      //设置卫星图为底图\r\n");
      out.write("// map.centerAndZoom(new BMap.Point(116.404, 39.915),12);                     // 初始化地图,设置中心点坐标和地图级别。\r\n");
      out.write("// map.addControl(new BMap.NavigationControl());  //添加鱼骨控件\r\n");
      out.write("// map.addControl(new BMap.MapTypeControl());          //添加地图类型控件\r\n");
      out.write("// map.setCurrentCity(\"北京\");\r\n");
      out.write("\r\n");
      out.write("// var map = new BMap.Map(\"map\");      //设置卫星图为底图\r\n");
      out.write("// map.centerAndZoom(new BMap.Point(121.487899, 31.249162),11);                     // 初始化地图,设置中心点坐标和地图级别。\r\n");
      out.write("// map.addControl(new BMap.NavigationControl());  //添加鱼骨控件\r\n");
      out.write("// map.addControl(new BMap.MapTypeControl());          //添加地图类型控件\r\n");
      out.write("// map.setCurrentCity(\"上海\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// var secRingCenter = new BMap.Point(116.400244,39.931757);\r\n");
      out.write("// var secRing = [new BMap.Point(116.362875,39.949459),new BMap.Point(116.378972,39.956539),new BMap.Point(116.438764,39.955654),new BMap.Point(116.440488,39.911836),new BMap.Point(116.365175,39.905637)];\r\n");
      out.write("// 创建多边形\r\n");
      out.write("// var secRingPolygon = new BMap.Polygon(secRing, {strokeColor:\"blue\", strokeWeight:5, strokeOpacity:0.5});\r\n");
      out.write("// 添加多边形到地图上\r\n");
      out.write("// map.addOverlay(secRingPolygon);\r\n");
      out.write("\r\n");
      out.write("// 鼠标放上去\r\n");
      out.write("// secRingPolygon.addEventListener(\"mouseover\",function(){\r\n");
      out.write("//     secRingPolygon.setStrokeColor(\"red\");\r\n");
      out.write("// });\r\n");
      out.write("// 鼠标离开\r\n");
      out.write("// secRingPolygon.addEventListener(\"mouseout\",function(){\r\n");
      out.write("//     secRingPolygon.setStrokeColor(\"blue\");\r\n");
      out.write("// });\r\n");
      out.write("// 鼠标点击\r\n");
      out.write("// secRingPolygon.addEventListener(\"click\",function(){\r\n");
      out.write("// \talert(0);\r\n");
      out.write("// \twindow.location=\"index.jsp\";\r\n");
      out.write("//     map.zoomIn();\r\n");
      out.write("//     secRingPolygon.setStrokeColor(\"orange\");\r\n");
      out.write("//     map.setCenter(secRingCenter);\r\n");
      out.write("   \r\n");
      out.write("// });\r\n");
      out.write("\r\n");
      out.write("// 创建标签  \r\n");
      out.write("// var secRingLabel = new BMap.Label(\"<b>北京市二环</b>，包括了东城区</br>和西城区。著名旅游景点有</br>天安门、故宫、后海、北海</br>公园、景山、南锣鼓巷等。\",{offset: new BMap.Size(-150,0), position: secRingCenter});  \r\n");
      out.write("// secRingLabel.setStyle({\"z-index\":\"999999\", \"padding\": \"10px\",\"width\": \"140px\",\"border\": \"1px solid #ccff00\"});  \r\n");
      out.write("  \r\n");
      out.write("// var secRingLabel2 = new BMap.Label(\"二  环\",{offset: new BMap.Size(10,-30), position: secRingCenter});  \r\n");
      out.write("// secRingLabel2.setStyle({\"line-height\": \"20px\", \"text-align\": \"center\", \"width\": \"80px\", \"height\": \"29px\", \"border\": \"none\", \"padding\": \"2px\",\"background\": \"url(http://jixingjx.com/mapapi/ac.gif) no-repeat\",});  \r\n");
      out.write("// map.addOverlay(secRingLabel2);  \r\n");
      out.write("  \r\n");
      out.write("// 创建海淀区  \r\n");
      out.write("// 创建经纬度数组  \r\n");
      out.write("// var haidianCenter = new BMap.Point(116.305958,39.969037);  \r\n");
      out.write("// var haidian = [new BMap.Point(116.352526,39.915599),new BMap.Point(116.278362,39.916485),new BMap.Point(116.252491,39.943042),new BMap.Point(116.234669,39.994358),new BMap.Point(116.281812,40.037239),new BMap.Point(116.281812,40.037239),new BMap.Point(116.386446,39.98684),new BMap.Point(116.389896,39.968263),new BMap.Point(116.336429,39.960299)];  \r\n");
      out.write("// 创建多边形  \r\n");
      out.write("// var haidianPolygon = new BMap.Polygon(haidian, {strokeColor:\"blue\", strokeWeight:5, strokeOpacity:0.5});  \r\n");
      out.write("// 添加多边形到地图上  \r\n");
      out.write("// map.addOverlay(haidianPolygon);  \r\n");
      out.write("// 给多边形添加鼠标事件  \r\n");
      out.write("// haidianPolygon.addEventListener(\"mouseover\",function(){  \r\n");
      out.write("//     haidianPolygon.setStrokeColor(\"red\");  \r\n");
      out.write("//     map.addOverlay(haidianLabel);  \r\n");
      out.write("//     map.panTo(haidianCenter);  \r\n");
      out.write("// });  \r\n");
      out.write("// haidianPolygon.addEventListener(\"mouseout\",function(){  \r\n");
      out.write("//     haidianPolygon.setStrokeColor(\"blue\");  \r\n");
      out.write("//     map.removeOverlay(haidianLabel);  \r\n");
      out.write("// });  \r\n");
      out.write("// haidianPolygon.addEventListener(\"click\",function(){  \r\n");
      out.write("//     map.zoomIn();  \r\n");
      out.write("//     haidianPolygon.setStrokeColor(\"orange\");  \r\n");
      out.write("//     map.setCenter(haidianCenter);  \r\n");
      out.write("// alert(0);\r\n");
      out.write("// });  \r\n");
      out.write("// 创建标签  \r\n");
      out.write("// var haidianLabel = new BMap.Label(\"<b>北京市海淀区</b>，是北京市</br>高等学府的聚集地。这里涵</br>括了北京市80%的重点大学</br>。其中清华、北大都是大家</br>耳熟能详的求学地。\",{offset: new BMap.Size(-150,0), position: haidianCenter});  \r\n");
      out.write("// haidianLabel.setStyle({\"z-index\":\"999999\", \"padding\": \"10px\",\"width\": \"140px\",\"border\": \"1px solid #ccff00\"});  \r\n");
      out.write("  \r\n");
      out.write("// var haidianLabel2 = new BMap.Label(\"海淀区\",{offset: new BMap.Size(10,-30), position: haidianCenter});  \r\n");
      out.write("// haidianLabel2.setStyle({\"line-height\": \"20px\", \"text-align\": \"center\", \"width\": \"80px\", \"height\": \"29px\", \"border\": \"none\", \"padding\": \"2px\",\"background\": \"url(http://jixingjx.com/mapapi/ac.gif) no-repeat\",});  \r\n");
      out.write("// map.addOverlay(haidianLabel2);  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" getBoundary();\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("var map = new BMap.Map(\"map\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var point = new BMap.Point(121.487899,31.249162);  // 创建点坐标\r\n");
      out.write("map.centerAndZoom(point, 10);\r\n");
      out.write("\r\n");
      out.write("map.addControl(new BMap.NavigationControl({type: BMAP_NAVIGATION_CONTROL_SMALL}));\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getBoundary(){       \r\n");
      out.write("    var bdary = new BMap.Boundary();\r\n");
      out.write("    var name = '黄浦区,徐汇区,松江区,奉贤区,嘉定区,宝山区,虹口区,闵行区,崇明县,闸北区,杨浦区,浦东新区,普陀区,长宁区,青浦区,静安区,金山区';\r\n");
      out.write("    var len=name.split(\",\");\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    for ( var y = 0; y < len.length; y++) {\r\n");
      out.write("    \t bdary.get(len[y], function(rs){  \r\n");
      out.write("    \t\t //获取行政区域\\\r\n");
      out.write("    \t        var count = rs.boundaries.length; \r\n");
      out.write("    \t\t var haidianCenter;\r\n");
      out.write("    \t\t var haidianLabel2;\r\n");
      out.write("//     \t\t alert(count);\r\n");
      out.write("    \t        for(var i = 0; i < count; i++){\r\n");
      out.write("    \t          var   ply = new BMap.Polygon(rs.boundaries[i], {strokeColor:\"blue\", strokeWeight:2, strokeOpacity:0.5}); //建立多边形覆盖物\r\n");
      out.write("    \t            map.addOverlay(ply);  //添加覆盖物\r\n");
      out.write("    \t           haidianCenter = new BMap.Point(121.446235,31.169152);\r\n");
      out.write("//     \t            alert(len[y]);\r\n");
      out.write("    \t           haidianLabel2 = new BMap.Label(len[y],{offset: new BMap.Size(0,0), position: ply});  \r\n");
      out.write("    \t            haidianLabel2.setStyle({\"line-height\": \"20px\", \"text-align\": \"center\", \"width\": \"80px\", \"height\": \"29px\", \"border\": \"none\", \"padding\": \"2px\",\"background\": \"url(http://jixingjx.com/mapapi/ac.gif) no-repeat\",});  \r\n");
      out.write("    \t            map.addOverlay(haidianLabel2);  \r\n");
      out.write("    \t        }                \r\n");
      out.write("    \t    });   \r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("//    给多边形添加鼠标事件  \r\n");
      out.write("//  ply.addEventListener(\"mouseover\",function(){  \r\n");
      out.write("//      haidianPolygon.setStrokeColor(\"red\");  \r\n");
      out.write("//      map.addOverlay(haidianLabel);  \r\n");
      out.write("//      map.panTo(haidianCenter);  \r\n");
      out.write("//  });  \r\n");
      out.write("//  ply.addEventListener(\"mouseout\",function(){  \r\n");
      out.write("//      haidianPolygon.setStrokeColor(\"blue\");  \r\n");
      out.write("//      map.removeOverlay(haidianLabel);  \r\n");
      out.write("//  });  \r\n");
      out.write("//  ply.addEventListener(\"click\",function(){  \r\n");
      out.write("//  alert(0);\r\n");
      out.write("//  });  \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
