package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ditu_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../site_media/js/jquery.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<title>水质检测</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" body,form,ul,li,a,ol,h1,h2,h3,h4,h5,h6,input,textarea,img{margin:0px;padding:0px;}  \r\n");
      out.write("ul,li,dl{list-style-type:none;} \r\n");
      out.write("a{text-decoration: none;}\r\n");
      out.write("body{font-size: 12px;font-family: \"Microsoft YaHei\";color:#777777; overflow:auto;background-color: #b0d7f9;position: relative;}\r\n");
      out.write(".w_div{width: 100%;height: 1000px;position:relative; }\r\n");
      out.write(".w_top{width: 100%;height: 50px;}\r\n");
      out.write(".w_top h1{text-align: center;font-weight: bold;color: black;font-size: 36px;margin-top: 5px;}\r\n");
      out.write(".w_content{width: 100%;height:auto;margin-top: 15px;position: absolute;}\r\n");
      out.write(".w_contentLeft{width: 60%; height: auto;float: left;margin-left: 10px;float: left;}\r\n");
      out.write(".w_contentRight{width: 33%;height: auto;float: left;margin: 0 0 0 10px;}\r\n");
      out.write(".w_logo{display: block;float: right;margin-top: -35px;margin-right: 30px;width: 70px;height: 40px;text-align: center;}\r\n");
      out.write(".w_conTop{width: 100%;float: left;height: 800px;border: 1px solid blue;margin-bottom: 25px;}\r\n");
      out.write(".w_conTop img{display: block;margin: auto;}\r\n");
      out.write(".w_conComm{width: 100%;height: auto;float: left;}\r\n");
      out.write(".w_conComm input{display: block; width: 300px;height: 50px;float: left;margin-left: 20%;font-size: 22px;}\r\n");
      out.write(".w_contentRight ul{width: 100%;height: 45px;}\r\n");
      out.write(".w_contentRight li{float: left;text-align: center;width: 49%; height: 40px;background-color: #e5e5e5;border-right-color: black;}\r\n");
      out.write(".w_contentRight a{color: black;font-size: 24px;}\r\n");
      out.write(".w_conTab{width: 100%;height: auto;margin-top: 0px;}\r\n");
      out.write(".w_conTab table{width: 100%;height: auto;text-align: center;border: 1px solid black;}\r\n");
      out.write(".w_conTab table caption{font-size: 22px;font-weight: bold;margin-bottom: 10px;}\r\n");
      out.write(".w_conTab table thead td{font-size: 22px;font-weight: 400;}\r\n");
      out.write(".w_conTab table td{font-size: 17px; border: 1px solid black;}\r\n");
      out.write(".w_conTab caption{font-size: 26px;}\r\n");
      out.write(".col{background-color: blue;color: white;}\r\n");
      out.write(".w_a{width: 100%;height: 35px;margin-bottom: 15px;}\r\n");
      out.write(".w_a a{display: block; float: left;width: 50%;text-align: center;background-color: #e5e5e5;}\r\n");
      out.write(".w_a a:hover{background-color: white;color: black;}\r\n");
      out.write(".w_conTab table tr th{ height:28px; line-height:28px; background:#999}\r\n");
      out.write(".w_conTab table tr td{ height:28px; line-height:28px; text-align:center;background:#eee0a7;vertical-align:middle;} \r\n");
      out.write("/* css注释：默认css背景被白色 */\r\n");
      out.write(".w_conTab table.stripe tr.alt td { background:#f5f7ea;} \r\n");
      out.write(".w_con1{background: url(../../site_media/img/album-bg1301.png) no-repeat;background-position:0px 0px;float: left;width: 30px;height: 100px;border: 1px solid blue;margin-top: 20%}\r\n");
      out.write(".w_con2{background: url(../../site_media/img/album-bg1301.png) no-repeat;background-position:0px 0px;float: left;width: 30px;height: 100px;border: 1px solid blue;margin-top: 20%}\r\n");
      out.write("/* .mapicon{width: 100%;height: auto;z-index: 900;} */\r\n");
      out.write(" .mapicon img{z-index: 900;width: 30px;height: 40px;position: absolute;} \r\n");
      out.write(".mapicon{width: 100%;height: auto;}\r\n");
      out.write(".mapdiv{width: 300px;height: 50px;position: absolute;}\r\n");
      out.write(".mapdiv table{width: 100%;text-align: center;}\r\n");
      out.write("/* .mapdiv table tr td{} */\r\n");
      out.write("#m1{background: red;border: 1px solid blue;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar stat;\r\n");
      out.write("\t\r\n");
      out.write("\t//初始化自来水公司信息\r\n");
      out.write("\tcom();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//行政区信息\r\n");
      out.write("$(\"#region\").click(function(){\r\n");
      out.write("\tstat=2;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".w_conTop\").empty();\r\n");
      out.write("\t$(\".w_conTop\").append(\"<img src='../../site_media/img/map2.jpg' width='950' height='800' border='0' usemap='#Map' style='z-index: 0;'/>\"\r\n");
      out.write("\t\t+\"<map name='Map' id='Map'><area shape='poly' coords='271,311,261,281,273,251,291,235,312,222,347,210,395,205,437,211,473,226,498,247,512,279,510,303,490,326,453,344,420,353,370,354,324,344' href='#' />\"\r\n");
      out.write("\t   +\"<area shape='poly' coords='334,434,314,404,333,380,365,365,405,357,444,357,486,365,514,375,535,398,530,419,507,437,469,452,425,454,371,449' href='#' />\" \r\n");
      out.write("\t   +\" <area shape='poly' coords='590,405,612,427,636,437,661,445,691,446,724,436,751,426,769,408,786,387,786,355,770,331,753,314,722,302,701,296,669,298,644,300,613,312,592,330,580,348,575,371' href='#' /> \"\r\n");
      out.write("\t\t+\"</map> <div class='mapicon' id='mapicon'> </div>\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"http://192.168.20.195:8000/hardsocket/getAreaAvgInfo?city_id=310000\",\r\n");
      out.write("\t\ttype:\"GET\",\r\n");
      out.write("// \t\t async: false, \r\n");
      out.write("// \t\t contenttype :\"application/x-www-form-urlencoded;charset=utf-8\", \r\n");
      out.write("// \t\tdata:{city_id:\"310000\"},\r\n");
      out.write("\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar json=eval(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".w_conTab\").empty();\r\n");
      out.write("\t\t\tvar con=\"<table cellpadding='0' cellspacing='0' id='conTab'><caption>行政区检测总览</caption><thead><tr><td></td><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr></thead>\";\r\n");
      out.write("\t\t\tfor ( var y = 0; y < json['area_info'].length; y++) {\r\n");
      out.write("\t\t\t\tcon+=\"<tr><td>\"+json['area_info'][y]['areaName']+\"</td><td>\"+json['area_info'][y]['area_ph']+\"</td><td>\"+json['area_info'][y]['area_conductivity']+\"</td><td>\"+json['area_info'][y]['area_DO']+\"</td><td>\"+json['area_info'][y]['area_rc']+\"</td><td>\"+json['area_info'][y]['area_turbidity']+\"</td><td>\"+json['area_info'][y]['area_temp']+\"</td></tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcon+=\"</table>\";\r\n");
      out.write("\t\t\t$(\".w_conTab\").append(con);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//检测点\r\n");
      out.write("\t\t\t$(\"#mapicon\").empty();\r\n");
      out.write("\t\t\tfor ( var x = 0;  x< json['spot_info'].length; x++) {\r\n");
      out.write("\t\t\t\tvar st=json['spot_info'][x]['spot_status'];\r\n");
      out.write("\t\t\t\tif(st==1){\r\n");
      out.write("\t\t\t\t\tvar img=\"<img src='../../site_media/img/icongreen.png' id='\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t \t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t}else if(st==0){\r\n");
      out.write("\t\t\t\t\tvar img=\"<img src='../../site_media/img/iconred.png' id='\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t \t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(XMLHttpRequest, textStatus, errorThrown){\r\n");
      out.write("            alert(XMLHttpRequest.status);\r\n");
      out.write("            alert(XMLHttpRequest.readyState);\r\n");
      out.write("            alert(textStatus);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}); \r\n");
      out.write("//自来水公司信息\r\n");
      out.write("$(\"#company\").click(com);\r\n");
      out.write("\r\n");
      out.write("//左右箭头滑动切换 \r\n");
      out.write("$(\"#w_con\").click(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"#w_con\").hasClass(\"w_con1\")){\r\n");
      out.write("\t\t$(\"#w_con\").removeClass(\"w_con1\");\r\n");
      out.write("\t\t$(\"#w_con\").addClass(\"w_con2\");\r\n");
      out.write("\t\t$(\".w_content\").stop(true,false).animate({\"left\":-500},500);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#w_con\").removeClass(\"w_con2\");\r\n");
      out.write("\t\t$(\"#w_con\").addClass(\"w_con1\");\r\n");
      out.write("\t\t$(\".w_content\").stop(true,false).animate({\"left\":0},500);\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//地图图标鼠标移出事件\r\n");
      out.write("$(\"#mapicon img\").live(\"mouseout\",function(){\r\n");
      out.write("\t//鼠标移出时删除div\r\n");
      out.write("\t$(\".mapdiv\").remove();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//地图图标鼠标放上去事件\r\n");
      out.write("$(\"#mapicon img\").live(\"mouseover\",function(){\r\n");
      out.write("\tvar id=$(this).attr(\"id\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar left=$(this).offset().left;\r\n");
      out.write("\tvar top=$(this).offset().top;\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"http://192.168.20.195:8000/hardsocket/getOneSpotInfo?spot_id=\"+id+\"\",\r\n");
      out.write("\t\ttype:\"GET\",\r\n");
      out.write("\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar json=eval(data);\r\n");
      out.write("\t\t\tvar mapdiv=\" <div class='mapdiv' style='top:\"+(top-50)+\"px;left:\"+left+\"px;' id='mapdiv'><table border='1' cellpadding='0' cellspacing='0'>\"\r\n");
      out.write("\t\t\t+\"<tr class='a'><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr>\"\r\n");
      out.write("\t\t\t+\"<tr class='b'><td>\"+json[\"spot_ph\"]+\"</td><td>\"+json[\"spot_conductivity\"]+\"</td><td>\"+json[\"spot_DO\"]+\"</td><td>\"+json[\"spot_rc\"]+\"</td><td>\"+json[\"spot_turbidity\"]+\"</td><td>\"+json[\"spot_temp\"]+\"</td></tr>\"\r\n");
      out.write("\t\t\t+\"</table></div>\";\r\n");
      out.write("\t\t\t$(\"body\").append(mapdiv);\r\n");
      out.write("\t\t\t//判断检测值不合格标识出来\r\n");
      out.write("\t\t\tif(json[\"ph_status\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(0)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(0)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}else if(json[\"spot_conductivity\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(1)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(1)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}else if(json[\"spot_DO\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(2)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(2)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}else if(json[\"spot_rc\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(3)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(3)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}else if(json[\"spot_turbidity\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(4)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(4)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}else if(json[\"spot_temp\"]==0){\r\n");
      out.write("\t\t\t\t$(\".a td:eq(5)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t\t$(\".b td:eq(5)\").attr(\"style\", \"border:1px solid red;color:red\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//地图图标鼠标点击事件\r\n");
      out.write("$(\"#mapicon img\").live(\"click\",function(){\r\n");
      out.write("\tvar id=$(this).attr(\"id\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"http://192.168.20.195:8000/hardsocket/getOneSpotInfo?spot_id=\"+id+\"\",\r\n");
      out.write("\t\ttype:\"GET\",\r\n");
      out.write("\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar json=eval(data);\r\n");
      out.write("\t\t\t$(\".w_conTab\").empty();\r\n");
      out.write("\t\t\tvar con=\"<table cellpadding='0' cellspacing='0' id='conTab'><caption>\"+json['corp_name']+json['area_name']+json['spot_name']+\"</caption><thead><tr><td></td><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr></thead>\";\r\n");
      out.write("\t\t\t\tcon+=\"<tr><td>\"+json['spot_name']+\"</td><td>\"+json['spot_ph']+\"</td><td>\"+json['spot_conductivity']+\"</td><td>\"+json['spot_DO']+\"</td><td>\"+json['spot_rc']+\"</td><td>\"+json['spot_turbidity']+\"</td><td>\"+json['spot_temp']+\"</td></tr>\";\r\n");
      out.write("\t\t\tcon+=\"</table>\";\r\n");
      out.write("\t\t\t$(\".w_conTab\").append(con);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//点击公司获取公司分公司的信息\r\n");
      out.write("\r\n");
      out.write("$(\"#Map area\").live(\"click\",function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar id=$(this).attr(\"id\");\r\n");
      out.write("\tif(stat==1){\r\n");
      out.write("\t\t//1说明是公司\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"http://192.168.20.195:8000/hardsocket/getOneCorpInfo/?corp_id=\"+id+\"\",\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("//\t \t\t async: false, \r\n");
      out.write("\t\t\t contentType:\"application/x-www-form-urlencoded;charset=UTF-8\", \r\n");
      out.write("//\t \t\tdata:{city_id:\"310000\"},\r\n");
      out.write("\t\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar json=eval(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".w_conTab\").empty();\r\n");
      out.write("\t\t\t\tvar con=\"<table cellpadding='0' cellspacing='0' id='conTab'><caption>\"+json['corp_info'][0]['corp_name']+\"</caption><thead><tr><td></td><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr></thead>\";\r\n");
      out.write("\t\t\t\tfor ( var y = 0; y < json['corp_info'].length; y++) {\r\n");
      out.write("\t\t\t\t\tcon+=\"<tr><td>\"+json['corp_info'][y]['corpChild_name']+\"</td><td>\"+json['corp_info'][y]['corp_ph']+\"</td><td>\"+json['corp_info'][y]['corp_conductivity']+\"</td><td>\"+json['corp_info'][y]['corp_DO']+\"</td><td>\"+json['corp_info'][y]['corp_rc']+\"</td><td>\"+json['corp_info'][y]['corp_turbidity']+\"</td><td>\"+json['corp_info'][y]['corp_temp']+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcon+=\"</table>\";\r\n");
      out.write("\t\t\t\t$(\".w_conTab\").append(con);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t\t\t\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t\t\t\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//检测点\r\n");
      out.write("\t\t\t\t$(\"#mapicon\").empty();\r\n");
      out.write("\t\t\t\tfor ( var x = 0;  x< json['spot_info'].length; x++) {\r\n");
      out.write("\t\t\t\t\tvar st=json['spot_info'][x]['spot_status'];\r\n");
      out.write("\t\t\t\t\tif(st==1){\r\n");
      out.write("\t\t\t\t\t\tvar img=\"<img src='../../site_media/img/icongreen.png' id='\"+json['spot_info'][x]['spot_id']+\"' style='width:40px;height:45px;'/>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t\t \t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t\t}else if(st==0){\r\n");
      out.write("\t\t\t\t\t\tvar img=\"<img src='../../site_media/img/iconred.png' id='\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t\t \t$(\"#\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(XMLHttpRequest, textStatus, errorThrown){\r\n");
      out.write("\t            alert(XMLHttpRequest.status);\r\n");
      out.write("\t            alert(XMLHttpRequest.readyState);\r\n");
      out.write("\t            alert(textStatus);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if(stat==2){\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar id=$(this).attr(\"id\");\r\n");
      out.write("\t\t//2说明是行政区\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"http://192.168.20.195:8000/hardsocket/getOneAreaInfo/?area_id=\"+id+\"\",\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("//\t \t\t async: false, \r\n");
      out.write("\t\t\t contentType:\"application/x-www-form-urlencoded;charset=UTF-8\", \r\n");
      out.write("//\t \t\tdata:{city_id:\"310000\"},\r\n");
      out.write("\t\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar json=eval(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".w_conTab\").empty();\r\n");
      out.write("\t\t\t\tvar con=\"<table cellpadding='0' cellspacing='0' id='conTab'><caption>\"+json['area_info'][0]['area_anme']+\"</caption><thead><tr><td></td><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr></thead>\";\r\n");
      out.write("\t\t\t\tfor ( var y = 0; y < json['area_info'].length; y++) {\r\n");
      out.write("\t\t\t\t\tcon+=\"<tr><td>\"+json['area_info'][y]['areaChild_name']+\"</td><td>\"+json['area_info'][y]['area_ph']+\"</td><td>\"+json['area_info'][y]['area_conductivity']+\"</td><td>\"+json['area_info'][y]['area_DO']+\"</td><td>\"+json['area_info'][y]['area_rc']+\"</td><td>\"+json['area_info'][y]['area_turbidity']+\"</td><td>\"+json['area_info'][y]['area_temp']+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcon+=\"</table>\";\r\n");
      out.write("\t\t\t\t$(\".w_conTab\").append(con);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t\t\t\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t\t\t\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//检测点\r\n");
      out.write("\t\t\t\t$(\"#mapicon\").empty();\r\n");
      out.write("\t\t\t\tfor ( var x = 0;  x< json['spot_info'].length; x++) {\r\n");
      out.write("\t\t\t\t\tvar st=json['spot_info'][x]['spot_status'];\r\n");
      out.write("\t\t\t\t\tif(st==1){\r\n");
      out.write("\t\t\t\t\t\tvar img=\"<img src='../../site_media/img/icongreen.png' id='1\"+json['spot_info'][x]['spot_id']+\"' style='width:40px;height:45px;'/>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t\t$(\"#1\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t\t \t$(\"#1\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t\t}else if(st==0){\r\n");
      out.write("\t\t\t\t\t\tvar img=\"<img src='../../site_media/img/iconred.png' id='1\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t\t$(\"#1\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t\t \t$(\"#1\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(XMLHttpRequest, textStatus, errorThrown){\r\n");
      out.write("\t            alert(XMLHttpRequest.status);\r\n");
      out.write("\t            alert(XMLHttpRequest.readyState);\r\n");
      out.write("\t            alert(textStatus);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function com(){\r\n");
      out.write("\t\r\n");
      out.write("\tstat=1;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".w_conTop\").empty();\r\n");
      out.write("\t$(\".w_conTop\").append(\"<img src='../../site_media/img/map1.jpg' width='950' height='800' border='0' usemap='#Map' style='z-index: 0;'/>\"\r\n");
      out.write("\t\t+\"<map name='Map' id='Map'><area shape='poly' coords='239,508,430,507,431,279,236,279' href='#' id='1' /> \"\r\n");
      out.write("\t\t+\"<area shape='poly' coords='455,542,700,545,701,749,456,749' href='#' id='2' /><area shape='poly' coords='508,426,739,427,738,219,504,213' href='#' id='3' /> </map> \"\r\n");
      out.write("\t\t+\"<div class='mapicon' id='mapicon'> </div>\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"http://192.168.20.195:8000/hardsocket/getAllCorpAvgInfo/?city_id=310000\",\r\n");
      out.write("\t\ttype:\"GET\",\r\n");
      out.write("// \t\t async: false, \r\n");
      out.write("\t\t contentType:\"application/x-www-form-urlencoded;charset=UTF-8\", \r\n");
      out.write("// \t\tdata:{city_id:\"310000\"},\r\n");
      out.write("\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\tjsonp:\"jsonpcallback\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar json=eval(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".w_conTab\").empty();\r\n");
      out.write("\t\t\tvar con=\"<table cellpadding='0' cellspacing='0' id='conTab'><caption>自来水公司检测总览</caption><thead><tr><td></td><td>PH值</td><td>电导率</td><td>溶解氧</td><td>余氯</td><td>浊度</td><td>水温</td></tr></thead>\";\r\n");
      out.write("\t\t\tfor ( var y = 0; y < json['corp_info'].length; y++) {\r\n");
      out.write("\t\t\t\tcon+=\"<tr><td>\"+json['corp_info'][y]['corp_name']+\"</td><td>\"+json['corp_info'][y]['corp_ph']+\"</td><td>\"+json['corp_info'][y]['corp_conductivity']+\"</td><td>\"+json['corp_info'][y]['corp_DO']+\"</td><td>\"+json['corp_info'][y]['corp_rc']+\"</td><td>\"+json['corp_info'][y]['corp_turbidity']+\"</td><td>\"+json['corp_info'][y]['corp_temp']+\"</td></tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcon+=\"</table>\";\r\n");
      out.write("\t\t\t$(\".w_conTab\").append(con);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*设置表格样式(偶数奇数切换颜色)*/\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr\").css(\"background-color\", \"#f5f7ea\");\r\n");
      out.write("\t\t\t$(\"#conTab\").find(\"tr:odd\").css(\"background-color\", \"#eee0a7\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//检测点\r\n");
      out.write("\t\t\t$(\"#mapicon\").empty();\r\n");
      out.write("\t\t\tfor ( var x = 0;  x< json['spot_info'].length; x++) {\r\n");
      out.write("\t\t\t\tvar st=json['spot_info'][x]['spot_status'];\r\n");
      out.write("\t\t\t\tif(st==1){\r\n");
      out.write("\t\t\t\t\tvar img=\"<img src='../../site_media/img/icongreen.png' id='0\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t$(\"#0\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t \t$(\"#0\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t}else if(st==0){\r\n");
      out.write("\t\t\t\t\tvar img=\"<img src='../../site_media/img/iconred.png' id='0\"+json['spot_info'][x]['spot_id']+\"'/>\";\r\n");
      out.write("\t\t\t\t\t$(\"#mapicon\").append(img);\r\n");
      out.write("\t\t\t\t\t$(\"#0\"+json['spot_info'][x]['spot_id']).css(\"top\",\"\"+json['spot_info'][x]['y_pos']+\"px\"); \r\n");
      out.write("\t\t\t\t \t$(\"#0\"+json['spot_info'][x]['spot_id']).css(\"left\",\"\"+json['spot_info'][x]['x_pos']+\"px\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(XMLHttpRequest, textStatus, errorThrown){\r\n");
      out.write("            alert(XMLHttpRequest.status);\r\n");
      out.write("            alert(XMLHttpRequest.readyState);\r\n");
      out.write("            alert(textStatus);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"w_div\">\r\n");
      out.write("\t\t<div class=\"w_top\"><h1>水质检测系统</h1><input type=\"button\" name=\"logo\" id=\"logo\" value=\"登录\" class=\"w_logo\"/></div>\r\n");
      out.write("\t\t<div class=\"w_content\">\r\n");
      out.write("\t\t\t<div class=\"w_contentLeft\">\r\n");
      out.write("\t\t\t\t<div class=\"w_conTop\" id=\"\">\r\n");
      out.write("<!-- \t\t\t\t\t<img src=\"../../site_media/img/map1.jpg\" width=\"950\" height=\"800\" border=\"0\" usemap=\"#Map\" style=\"z-index: 0;\" /> -->\r\n");
      out.write("<!-- \t\t\t\t\t<map name=\"Map\" id=\"Map\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t <area shape=\"poly\" coords=\"239,508,430,507,431,279,236,279\" href=\"#\" /> -->\r\n");
      out.write("<!-- \t\t\t\t\t    <area shape=\"poly\" coords=\"455,542,700,545,701,749,456,749\" href=\"#\" /> -->\r\n");
      out.write("<!-- \t\t\t\t\t    <area shape=\"poly\" coords=\"508,426,739,427,738,219,504,213\" href=\"#\" /> -->\r\n");
      out.write("<!-- \t\t\t\t\t </map> -->\r\n");
      out.write("<!-- \t\t\t\t\t <div class=\"mapicon\" id=\"mapicon\"> -->\r\n");
      out.write("\t\t\t\t\t<!--检测点  --> \t\r\n");
      out.write("<!-- \t\t\t\t\t </div> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w_con1\" id=\"w_con\"></div>\r\n");
      out.write("\t\t\t<div class=\"w_contentRight\">\r\n");
      out.write("\t\t\t<div class=\"w_a\"><a href=\"#\">水质报表</a><a href=\"#\">水质趋势图</a></div>\r\n");
      out.write("\t\t\t\t<div class=\"w_conTab\">\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"w_conComm\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"company\" id=\"company\" value=\"自来水公司分布图\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"region\" id=\"region\" value=\"上海行政区分布图\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
